### ISSUE TITLE
train_rlhf-trlx.py代码问题

### ISSUE THREAD

**Issue by taofennanhai** [sunzeyeah/RLHF#15]
我在用glm-large-chinese作为sft模型测试train_rlhf-trlx.py 代码的过程中报出错误

1. [再models包中的ppo.py代码中第574行](https://github.com/sunzeyeah/RLHF/blob/6439975a687fda49212210af2ef0598af49ea72d/src/models/ppo.py#L574)，函数hf_get_decoder_final_norm获取final_norm获取不到
```
一种我实现可行的方案是在norm_attrs添加了一行"glm.transformer.final_layernorm"，你看是否正确
def hf_get_decoder_final_norm(model: nn.Module) -> float:
    """Returns the final (layer) norm of the specified decoder.
    NOTE: Different model configurations have different final norm attribute names.
        - transformer.ln_f: (GPT2LMHeadModel, GPTJForCausalLM)
        - model.decoder.final_layer_norm: (OPTForCausalLM)
        - gpt_neox.layers.final_layer_norm: (GPTNeoXForCausalLM)
    """
    norm_attrs = (
        "transformer.ln_f",
        "model.decoder.final_layer_norm",
        "decoder.final_layer_norm",
        "gpt_neox.final_layer_norm",
        "glm.transformer.final_layernorm",
    )
    return findattr(model, norm_attrs)
```
2. [再models包中的ppo.py代码中第575行](https://github.com/sunzeyeah/RLHF/blob/6439975a687fda49212210af2ef0598af49ea72d/src/models/ppo.py#LL575C6-L575C60)，函数hf_get_lm_head获取lm_head获取为none，我看了model_glm的源码，[貌似是使用使用word_embedding作为线性层来作为lm_head](https://huggingface.co/THUDM/glm-large-chinese/blob/230f54e413fab4bc8f29bd3508aab301d757ef3e/modeling_glm.py#L787)
```
那下面代码是不是需要修改
def hf_get_lm_head(model: nn.Module) -> nn.Module:
    """Returns the language modeling (lm) head of the specified HuggingFace
    transformers model.
    NOTE: Different model configurations have different `lm_head` attribute names.
        - lm_head: (GPT2LMHeadModel, BloomForCausalLM)
        - embed_out: (GPTNeoXForCausalLM)
    """
    return model.get_output_embeddings()
```
3.[在T5brach中](https://github.com/sunzeyeah/RLHF/blob/6439975a687fda49212210af2ef0598af49ea72d/src/models/ppo.py#LL1267C9-L1267C58)，self.dropout = hf_get_decoder(base_model).dropout报错。
```
以下代码该如何修改，我目前不是很清楚这部分获取的是模型的哪个部分
def hf_get_decoder(model: nn.Module) -> nn.Module:
    """Returns the causal decoder backbone of the specified HuggingFace transformers
    model.
    NOTE: Different model configurations have different causal decoder attribute
    names.
        - transformer: (GPT2LMHeadModel, GPTJConfig)
        - model.decoder: (OPTConfig, BloomConfig)
        - gpt_neox: (GPTNeoXConfig)
    """
    decoder_attrs = ("transformer", "model.decoder", "gpt_neox", "decoder")
    return findattr(model, decoder_attrs)
```
这里具体报错的信息是
```
ValueError: Could not find an attribute from `('transformer', 'model.decoder', 
'gpt_neox', 'decoder')` in `GLMForConditionalGeneration(
  (glm): GLMModel(
    (word_embeddings): VocabEmbedding()
    (transformer): GLMStack(
      (embedding_dropout): Dropout(p=0.1, inplace=False)
      (position_embeddings): Embedding(1025, 1024)
      (block_position_embeddings): Embedding(1025, 1024)
```

**Comment by sunzeyeah** [comment]
抱歉 train_rlhf-trlx.py代码现在没有在维护了，因为考虑到trlx框架对deepspeed的支持不太好，而且框架比较复杂。最新的rlhf代码实现是基于[DeepSpeedChat](https://github.com/microsoft/DeepSpeedExamples/tree/master/applications/DeepSpeed-Chat)实现的，详见[train_rlhf.py](https://github.com/sunzeyeah/RLHF/blob/master/src/train_rlhf.py)

**Comment by taofennanhai** [comment]
很感谢。另外请问下[DeepSpeedChat](https://github.com/microsoft/DeepSpeedExamples/tree/master/applications/DeepSpeed-Chat)支持的不是只有官网的那几个模型吗，可以支持GLM或者chatGLM吗？

**Comment by sunzeyeah** [comment]
对的 目前还没有支持中文的这些预训练模型。不过只是不能使用deepspeed hybird engine，但是代码还可以跑通的。如果要用到hybrid engine，就需要自己写相关的模型类了
