### ISSUE TITLE
reward推理问题

### ISSUE THREAD

**Issue by ItGirls** [sunzeyeah/RLHF#16]
你好,请问你有没有发现在基于chatglm实现的reward模型做推理时,batchsize设置不同时,同一个样本推理结果不一致.model.eval,with torch.nograd这些都加了,还不清楚为什么会这样.

**Comment by ItGirls** [comment]
这里哈,在reward Model(base model为 chatglm)里面, 这个` hidden_states = hidden_states.view(batch_size, seq_len, hidden_size)`是错的,应该是` hidden_states = hidden_states.permute(1, 0, 2)`.

**Comment by sunzeyeah** [comment]
谢谢指出，已修复
