### ISSUE TITLE
chatglm+RLHF

### ISSUE THREAD

**Issue by MAJIN123** [sunzeyeah/RLHF#18]
能否支持使用chatglm进行领域内强化学习这条路呀。有这个需要😭

**Comment by sunzeyeah** [comment]
我们目前做的也是领域内的训练，SFT和Reward都是可以跑通的，但是因为RLHF需要同时加载SFT和Reward模型并进行训练，所以GPU硬件要求更高。

如果要做6B模型的RLHF训练，开启LoRA的情况下，预估起码要48G的显存。不过目前RLHF的代码在开启deepspeed stage 3的情况，并没有开启模型并行，可以参考[issue 13](https://github.com/sunzeyeah/RLHF/issues/13#issuecomment-1551376391)，后续会进行优化
