### ISSUE TITLE
pretrain_data_v1.jsonl 文件在哪里

### ISSUE THREAD

**Issue by Liufeiran123** [sunzeyeah/RLHF#24]
pretrain_data_v1.jsonl 这个文件在哪里，什么样的格式。有格式样例吗？

**Comment by sunzeyeah** [comment]
格式可以整理成这样：
```json
[
    {"prompt": ""},
]
```
或者
```json
[
    {"prompt": "", "label": ""},
]
```
看具体的预训练数据是什么样的，比如：问答类的数据更适合第2种

**Comment by Liufeiran123** [comment]
好的，非常感谢，train_data_external_v1.jsonl 这个文件的格式是什么样的呀。麻烦说下。

**Comment by sunzeyeah** [comment]
格式如下：
```json
[
    {"system": "", "prompt": "", "answers": [{"answer": "", "score": 1.0}]}
]
```
```system```表示全局性的instruction，```prompt```表示模型输入，```answer```表示模型输出，即监督值

**Comment by Liufeiran123** [comment]
预训练的话，如果是纯txt文本数据，不是QA数据的话，应该把txt拼接成一行，放在
[
    {"prompt": "txt拼接一行数据"},
]
这里是吧

**Comment by sunzeyeah** [comment]
是的

> 预训练的话，如果是纯txt文本数据，不是QA数据的话，应该把txt拼接成一行，放在 [ {"prompt": "txt拼接一行数据"}, ] 这里是吧
