### ISSUE TITLE
RLHF相关问题

### ISSUE THREAD

**Issue by taofennanhai** [sunzeyeah/RLHF#5]
请问GLM-10B-Chinese的模型进行RLHF大概需要多大GPU？

**Comment by taofennanhai** [comment]
感谢你的回复！我大致了解了训练过程所需要的GPU显存消耗了。
我还有两个疑问，请教下：
1.GLM-10B-Chinese支持LoRA吗？我看官方仓库中是没有的
2.还有就是trlx是否训练的过程支持deepspeed框架？如果有，是在哪设置的？

**Comment by sunzeyeah** [comment]
1. 目前已实现了LoRA，具体可参考[lora.py](https://github.com/sunzeyeah/RLHF/blob/master/src/models/lora.py)和[train_sft.py](https://github.com/sunzeyeah/RLHF/blob/master/src/train_sft.py#129)第129行
2. trlx用的是huggingface的accelerate框架，是支持deepspeed的，但目前RHLF的代码还在调试阶段。有兴趣的话，可以参考[accelerate官方样例](https://github.com/huggingface/accelerate/blob/main/README.md)的**Launching training using DeepSpeed**部分，不过accelerate对deepspeed的支持还是实验性的。除此之外，DeepSpeed也开源了自己的RLHF训练代码，可以参考[DeepSpeed-Chat](https://github.com/microsoft/DeepSpeedExamples/tree/master/applications/DeepSpeed-Chat)。后续计划对这部分代码进行实验和调试，如果效果ok，会参考他们的实现调整当前的RLHF代码。

**Comment by taofennanhai** [comment]
非常感谢！
